### ISSUE TITLE
configure secure dojo deployment

### ISSUE THREAD

**Issue by navpreetkaur051** [navpreetkaur051/securedojo#16]

**Comment by navpreetkaur051** [comment]
Inprogress

**Comment by mingganz** [comment]
Deploy customized SecureCodingDojo on google cloud and here are the URIs:
http://dojo.ottawaontario.ml
http://dojo.ottawaontario.ml:81

**Comment by navpreetkaur051** [comment]
works fine : http://dojo.ottawaontario.ml:81
