### ISSUE TITLE
Root folder is not password protected- Please resolve

### ISSUE THREAD

**Issue by mshshuvo** [navpreetkaur051/securedojo#31]
![Screenshot_15](https://user-images.githubusercontent.com/70147942/109420533-0675a180-79a1-11eb-8c42-1aff347ee67c.png)

**Comment by mingganz** [comment]
@navpreetkaur051  I suppose this is for adim app.

**Comment by navpreetkaur051** [comment]
This is secure heroku environment and also we cannot control this as it is in control of provider.
